on:
  push:
    branches: [ "gh-pages" ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - uses: na1307/blazor-github-pages@v2
        id: prepare
        with:
          project-path: Samples/Nodsoft.MoltenObsidian.Samples.HttpWasm/Nodsoft.MoltenObsidian.Samples.HttpWasm.csproj
          main-repo: false
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.prepare.outputs.wwwroot-path }}
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment