env:
  PUBLISH_DIR: Samples/Nodsoft.MoltenObsidian.Samples.HttpWasm/bin/Release/net8.0/publish/wwwroot
on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet publish Samples/Nodsoft.MoltenObsidian.Samples.HttpWasm
      - uses: SteveSandersonMS/ghaction-rewrite-base-href@5b54862a8831e012d4f1a8b2660894415fdde8ec # v1.1.0
        with:
          html_path: ${{ env.PUBLISH_DIR }}/index.html
          base_href: /MoltenObsidian/
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PUBLISH_DIR }}
      - uses: actions/deploy-pages@v4
        id: deployment